const lyrics = [
    { time: 0, text: "Are you ready, hey, are you ready for this?", singer: "freddie" },
    { time: 2, text: "Are you hanging on the edge of your seat?", singer: "freddie" },
    { time: 4, text: "I need a break beat, uh", singer: "others" },
    { time: 5, text: "Are you ready, hey, are you ready for this?", singer: "freddie" },
    { time: 7, text: "Are you hanging on the edge of your seat?", singer: "freddie" },
    { time: 9, text: "I need a break beat, uh", singer: "others" },
    { time: 11, text: "Are you ready, hey, are you ready for this?", singer: "freddie" },
    { time: 13, text: "Are you hanging on the edge of your seat?", singer: "freddie" },
    { time: 15, text: "I need a break beat, uh", singer: "others" },
    { time: 16, text: "Outta the doorway the bullets rip", singer: "freddie" },
    { time: 20, text: "Repeating to the sound of the beat, hey", singer: "freddie" },

    { time: 22, text: "Yo, a for the kids in the club that's ready to get bugged", singer: "others" },
    { time: 24, text: "Another one bites the dust", singer: "freddie" },
    { time: 26, text: "And for the thugs with the burners that wanna blast off", singer: "others" },
    { time: 28, text: "Another one bites the dust", singer: "freddie" },
    { time: 30, text: "And for the kids on the blocks, shootin' at the crooked cops—blaow!", singer: "others" },
    { time: 32, text: "Another one bites the dust", singer: "freddie" },
    { time: 34, text: "And another one gone", singer: "freddie" },
    { time: 36, text: "And another one gone", singer: "freddie" },
    { time: 38, text: "Another one bites the dust", singer: "freddie" },
    { time: 40.1, text: "Young Free, Freddie where you at?", singer: "others" },

    { time: 41, text: "Steve walks wearily down the street", singer: "freddie" },
    { time: 43.9, text: "With the brim pulled way down low", singer: "freddie" },
    { time: 45, text: "Some cat up in Brooklyn just got robbed with a Kangol", singer: "others" },
    { time: 46, text: "Are you ready, hey, are you ready for this?", singer: "others" },
    { time: 48, text: "Are you hanging on the edge of your seat?", singer: "others" },
    { time: 50, text: "Out of the doorway, the bullets rip", singer: "freddie" },
    { time: 53, text: "Repeating to the sound of the beat, hey", singer: "freddie" },
    { time: 56, text: "My man got shot, and the block got hot", singer: "others" },
    { time: 58, text: "Another one bites the dust", singer: "freddie" },
    { time: 60, text: "Yo, hey I hear more shots, this is like Fort Knox, kid", singer: "others" },
    { time: 62, text: "Another one bites the dust", singer: "freddie" },
    { time: 64, text: "Hold your breath", singer: "others" },
    { time: 66, text: "Hold your breath", singer: "others" },
    { time: 68, text: "Hold your breath", singer: "others" },
    { time: 70, text: "Another one bites the dust", singer: "freddie" },

    { time: 72, text: "If you're a soldier at ease", singer: "others" },
    { time: 74, text: "My military style is known to murder Nazis", singer: "others" },
    { time: 76, text: "Brooklyn to Germany (Oh yeah) come on", singer: "others" },
    { time: 78, text: "My kamikaze will blow the U2", singer: "others" },
    { time: 80, text: "They hire Idi Amin in Timbuktu", singer: "others" },
    { time: 82, text: "Whether you Hindu, or do the Voodoo", singer: "others" },
    { time: 84, text: "You can't foresee this unless I bring the previews, yeah, yeah", singer: "others" },
    { time: 86, text: "Yo, it's the number one rappin' band (Come on)", singer: "others" },
    { time: 88, text: "Yo, this review will be critically acclaimed", singer: "others" },
    { time: 90, text: "Leave you in critical pain, clinically insane", singer: "others" },
    { time: 92, text: "The name Wyclef Jean, with a yes, yes y'all", singer: "others" },
    { time: 94, text: "Better have a vest y'all, I'll blast, and bless y'all (Oh yeah)", singer: "others" },
    { time: 96, text: "F-y'all, the mark of the beast, the triple six", singer: "others" },
    { time: 98, text: "Time running out, listen to the tick (Oh yeah)", singer: "others" },
    { time: 100, text: "If you see what I saw, then you seen what I seen", singer: "others" },
    { time: 102, text: "If you know what I know, you know what I mean (Oh yeah)", singer: "others" },
    { time: 104, text: "Commanding officer of the Navy SEAL team", singer: "others" },
    { time: 106, text: "Once I give the orders, you feel the infrared beam (Oh yeah) Blaow!", singer: "others" },
    { time: 108, text: "For all you critics, sayin' 'another remake'", singer: "others" },
    { time: 110, text: "Another one bites the dust", singer: "freddie" },
    { time: 112, text: "Yo, if you know the deal, this is the master reel, kid", singer: "others" },
    { time: 114, text: "Another one bites the dust (Oh yeah)", singer: "freddie" },
    { time: 116, text: "And another one gone", singer: "freddie" },
    { time: 118, text: "And another one gone", singer: "freddie" },
    { time: 120, text: "Another one bites the dust, hey", singer: "freddie" },
    { time: 122, text: "Freddie Mercury, where you at yo?", singer: "others" },
    { time: 124, text: "How do you think I'm gonna get along", singer: "freddie" },
    { time: 126, text: "Without you when you're gone (Oh yeah)", singer: "freddie" },
    { time: 128, text: "I need a break yo", singer: "others" },
    { time: 130, text: "If you're ready for the first of the month", singer: "others" },
    { time: 132, text: "For that welfare check, come on (Kicked me out on my own)", singer: "others" },
    { time: 134, text: "I need a break beat", singer: "others" },
    { time: 136, text: "Are you happy, are you satisfied?", singer: "freddie" },
    { time: 138, text: "How long can you stand the heat?", singer: "freddie" },
    { time: 140, text: "I need a break beat", singer: "others" },
    { time: 142, text: "Outta the doorway, the bullets rip", singer: "freddie" },
    { time: 144, text: "To the sound of the beat, look out", singer: "freddie" },
    { time: 146, text: "Yo, bulletproof vests, like the wild, wild west", singer: "others" },
    { time: 148, text: "Another one bites the dust", singer: "freddie" },
    { time: 150, text: "Yo, this is a stickup, now take off your Rolex", singer: "others" },
    { time: 152, text: "Another one bites the dust", singer: "freddie" },
    { time: 154, text: "Yo, dirty money, good money, yo it's all money-money", singer: "others" },
    { time: 156, text: "Another one bites the dust", singer: "freddie" },
    { time: 158, text: "Yo, Dirty Cash", singer: "others" },
    { time: 160, text: "Dirty Cash", singer: "others" },
    { time: 162, text: "The adventures of Dirty Cash", singer: "others" },
    { time: 164, text: "Another one bites the dust", singer: "freddie" },
    { time: 166, text: "Yo, for the love for the cash, I'll blast you in my path", singer: "others" },
    { time: 168, text: "Keep my eyes on the math, you cats don't know the half (Oh yeah)", singer: "others" },
    { time: 170, text: "As far as I'm concerned, you cats can burn in flames", singer: "others" },
    { time: 172, text: "This ain't no game, I'mma start callin' names (Oh yeah)", singer: "others" },
    { time: 174, text: "So come get me, if you know the one-fifty", singer: "others" },
    { time: 176, text: "A million refugees ready to bust with me (Oh yeah)", singer: "others" },
    { time: 178, text: "Bloody, filthy, in this rap shhh—", singer: "others" },
    { time: 180, text: "You gonna have to kill me, since you can't beat me (Oh yeah)", singer: "others" },
    { time: 182, text: "Pras, Dirty, Cash, you're the greedy", singer: "others" },
    { time: 184, text: "Believe me, you gotta let me fly like R. Kelly (Oh yeah)", singer: "others" },
    { time: 186, text: "Bite another dust with my man Freddie Mercury", singer: "others" },
    { time: 188, text: "What height nineties got ya cash, wannabe crazy (Oh yeah/Navy SEAL!)", singer: "others" },

    { time: 190, text: "Yo, I know you wanna see the Can-I-Bus bite the dust", singer: "others" },
    { time: 192, text: "So you could bury my body below the Earth's crust (Oh yeah)", singer: "others" },
    { time: 194, text: "But I'm a Small Soldier, to stay as focused", singer: "others" },
    { time: 196, text: "With guts, I rip the scab off of layin' the cut (Oh yeah)", singer: "others" },
    { time: 198, text: "I'm an extraordinary military mercenary", singer: "others" },
    { time: 200, text: "Searchin' for extra intelligence like steady (Oh yeah)", singer: "others" },
    { time: 202, text: "My rhymes cut through the radio waves like machetes", singer: "others" },
    { time: 204, text: "The predator becomes the prey in the Serengeti (Oh yeah)", singer: "others" },
    { time: 206, text: "I breach national security purposely", singer: "others" },
    { time: 208, text: "To safely return the statue of Freddy Mercury (Oh yeah)", singer: "others" },
    { time: 210, text: "Verbally, Wyclef, Pras and Free", singer: "others" },
    { time: 212, text: "Holdin' it down for the Refugee Navy SEALs Team (Oh yeah) (Navy SEALs)", singer: "others" },
    { time: 214, text: "Practically, I tactically destroy", singer: "others" },
    { time: 216, text: "Deploy more decoys than a presidential convoy (Oh yeah)", singer: "others" },
    { time: 218, text: "My whole envoy stay camouflaged out", singer: "others" },
    { time: 220, text: "And when I walk the street, I take the refugee route (Oh yeah)", singer: "others" },
    { time: 222, text: "This one go out to all my thugs in the borough", singer: "others" },
    { time: 224, text: "Soldiers stay thorough, like Kilamanjaro (Oh yeah)", singer: "others" },
    { time: 226, text: "Split it with an arrow, my girl platoon roll", singer: "others" },
    { time: 228, text: "Outta control, the female Mandingos (Oh yeah)", singer: "others" },
    { time: 230, text: "Free, I evolve from the egg of a seminarian", singer: "others" },
    { time: 232, text: "Don't go down, 'cause I'm a vegetarian (Oh yeah)", singer: "others" },
    { time: 234, text: "And when I bust, it ain't 'in God we trust'", singer: "others" },
    { time: 236, text: "And if you bring a gun, you better bring a black tusk (Oh yeah)", singer: "others" },

    { time: 238, text: "She looked into my eyes and said FBI", singer: "others" },
    { time: 240, text: "Another one bites the dust (Oh yeah)", singer: "freddie" },
    { time: 242, text: "She said she loved me, she was a spy who lied", singer: "others" },
    { time: 244, text: "Another one bites the dust", singer: "freddie" },
    { time: 246, text: "I could relate, could you relate?", singer: "others" },
    { time: 248, text: "Another one bites the dust", singer: "freddie" },
    { time: 250, text: "Jerry 'Wonda', The Product (Oh-oh)", singer: "others" },
    { time: 252, text: "Another one bites the dust", singer: "freddie" },
    { time: 254, text: "Yo, Canibus, John Forté (Don't you know we coming for you?)", singer: "others" },
    { time: 256, text: "Another one bites the dust", singer: "freddie" },
    { time: 258, text: "Yo, Dirty Cash, and baby Free", singer: "others" },
    { time: 260, text: "Another one bites the dust", singer: "freddie" },
    { time: 262, text: "And another one gone", singer: "freddie" },
    { time: 264, text: "And another one gone", singer: "freddie" },
    { time: 266, text: "Another one bites the dust, yeah", singer: "freddie" },
    { time: 268, text: "I'm out baby", singer: "others" },
    { time: 270, text: "Navy SEALs!", singer: "others" },
    { time: 272, text: "Another one bites the dust", singer: "freddie" },
    { time: 274, text: "Another one bites the dust", singer: "freddie" },
    { time: 276, text: "Another one bites the dust", singer: "freddie" },
];

let currentLyricIndex = 0;
const audio = document.getElementById("audio");
const lyricFreddieElement = document.getElementById("lyric-freddie");
const lyricOthersElement = document.getElementById("lyric-others");

audio.addEventListener("play", () => {
    setInterval(displayLyrics, 100);
});

function displayLyrics() {
    const currentTime = audio.currentTime;
    if (currentLyricIndex < lyrics.length && currentTime >= lyrics[currentLyricIndex].time) {
        if (lyrics[currentLyricIndex].singer === "freddie") {
            lyricFreddieElement.textContent = lyrics[currentLyricIndex].text;
        } else {
            lyricOthersElement.textContent = lyrics[currentLyricIndex].text;
        }
        currentLyricIndex++;
    }
}
